export default interface CatUnidadResponsable {
    clave: null | string,
    descripcion: string,
    descripcion_corta: string,
    tipo_unidad: string,
    titular: string,
    subdirector: string,
    dependencia: string|number,
    codigo_postal: string,
    telefono: string,
    extension: string,
    calle: string,
    numero_exterior: string,
    numero_interior: null | string,
    colonia: string,
    folio_licitacion: null | string,
    folio_contratacion: null | string,
    nombre_contrato: null | string,
    nombre_jefe_laboratorio: null | string,
    entidad: string|number,
}